### ISSUE TITLE
DOM is re-arranged when Politespace is activated

### ISSUE THREAD

**Issue by caseytrombley** [filamentgroup/politespace#30]
If you have an `input` that uses Politespace, and say you have a `span` or some other DOM above or below the `input` it seems that Politespace will flip the position of these elements so that whatever was below the `input` becomes on top (and vice versa).
This requires me to wrap the `input` with a `span` or `div` which is not ideal.

**Comment by zachleat** [comment]
I believe this was fixed with https://github.com/filamentgroup/politespace/commit/2ce813cd4c19b183ad86108b6590d246fc910cef (v0.1.17). Please reopen if this is not the case!

**Comment by dpouliot** [comment]
@zachleat I don't see release notes in your releases. we are running 1.6b, and wondering if we should update (would there be any downsides to look out for)?
