### ISSUE TITLE
add pre-built file on npm

### ISSUE THREAD

**Issue by maruilian11** [filamentgroup/politespace#47]
hi, recently we add your lib on https://cdnjs.com by manually building, could you please consider adding pre-build file on npm package so that we can use **npm auto-update** to add later released versions automatically.
thank you very much!

https://cdnjs.com/libraries/politespace
https://github.com/cdnjs/cdnjs/issues/7407

**Comment by zachleat** [comment]
Included as of v0.1.16

**Comment by maruilian11** [comment]
thanks a lot!
