### ISSUE TITLE
Working Webpack/Angular2 example

### ISSUE THREAD

**Issue by arloduff** [filamentgroup/politespace#80]
Is it possible to get an example of this working with Webpack and possibly also Angular2?

I'm trying to import the built file in the `vendor.js` file with the following:

    import 'node_modules/politespace/dist/politespace.js

And am triggering the `enhance` event on `document` every time the page changes in an Angular2 project like so:

    export class AppComponent {
      constructor (private router: Router) {
        router.events.subscribe((val) => {
          $(document).trigger("enhance");
        });
      }
    }

But I get an error on https://github.com/filamentgroup/politespace/blob/master/dist/politespace.js#L314 that Politespace is not defined.

Tracing the code to where `Politespace` is supposed to be defined, I can see that on https://github.com/filamentgroup/politespace/blob/master/dist/politespace.js#L189 in the demo code in this project, `w` is the Window object, whereas in Webpack, it seems to be an empty object, which is why line 314 above isn't recognizing `Politespace`.

**Comment by zachleat** [comment]
Politespace is now using UMD with 1.0. It should work correctly.
