### ISSUE TITLE
data-politespace-us-telephone error

### ISSUE THREAD

**Issue by caraclarke** [filamentgroup/politespace#81]
I listed my angularjs input box code below. I'm getting an error when I add `data-politespace-us-telephone` to the input box where if I try to enter a phone number starting with a `1` it registers as invalid. Is there a better attribute I could use to trim the beginning `1` off the input or another way to fix this?

`<input
        id="phoneNumber"
        name="phoneNumber"
        numbers-only
        ng-model="form.phoneNumber"
        type="tel"
        required
        maxlength="12"
        ng-minlength="10"
        date-pattern="/^[0-9]$*/"
        ng-maxlength="12"
        data-politespace
        data-grouplength="3,3,4"
        data-politespace-us-telephone
        data-delimiter="-"
        >`

**Comment by zachleat** [comment]
I’d recommend checking out the markup on http://filamentgroup.github.io/politespace/demo/demo.html#tels

Note that the `1` country code is stripped out if you type it in (and maxlength is automatically adjusted to allow typing more characters)

See: https://github.com/filamentgroup/politespace/blob/master/src/politespace-us-telephone.js#L43

Please reopen if you have more questions!
