### ISSUE TITLE
Unable to use arrows or forward-delete inside a Politespace input using Firefox browser

### ISSUE THREAD

**Issue by caseytrombley** [filamentgroup/politespace#82]
A user is not able to use arrow keys to move the type cursor back and forth in the input or use forward-delete key. 

This has been reported and confirmed in Firefox.

Please see screen shot for example.

<img width="904" alt="screen shot 2017-01-24 at 2 12 05 pm" src="https://cloud.githubusercontent.com/assets/472921/22262525/48797ed8-e23f-11e6-953b-0fb9d5e201e1.png">

**Comment by zachleat** [comment]
Hmm, I can’t reproduce this. Is it still an issue? Please reopen if so. http://filamentgroup.github.io/politespace/demo/demo.html#tels
