### ISSUE TITLE
data-politespace-delimiter cannot be . (dot)

### ISSUE THREAD

**Issue by joaomarcosmareto** [filamentgroup/politespace#89]
I am using this mask which is great, by the way. But I need the data-politespace-delimiter being dot, for brazilian money.
For example, R$ 4.500,00 (in Brazil, thousand delimiter is dot and decimal delimiter is comma).
Is there a way in which I can accomplish this task?

**Comment by codestellar** [comment]
@joaomarcosmareto True that! but you can add a ". " (Dot Space) and then replace ". " with "." on blur
