### ISSUE TITLE
Set data-grouplength dynamically

### ISSUE THREAD

**Issue by ryanburnette** [filamentgroup/politespace#9]
A straightforward way to call `jQuery.politespace()` again to change attributes would be nice. I wanted to do that today and had to call `jQuery.unbind()` on the element then wrote a little helper to set my attributes.

I also initially tried setting attributes on the element with `jQuery.data()` then `jQuery.prop()` but found that the attributes were only read when I got the DOM object and used `setAttribute()`. I'm curious to know why this is the case or if I missed something.

**Comment by ryanburnette** [comment]
I should have been more specific. I was using `jQuery.data()` to set the `data-grouplength` attribute. It had no effect. Once I switched to vanilla `getAttribute` and called the `jQuery.politespace()` method on my input again, it updated. So my code looks something like this, tweaked for testing:

```javascript
var $el, el;

$el = $("input").eq(0);
el = $("input").get(0);

el.setAttribute("data-grouplength", "4,4,4,4");

$el.politespace();
```

... and using that pattern I'm able to change the grouplength based on other factors. Am I making it harder than it needs to be?

**Comment by ryanburnette** [comment]
I was having this issue because `jQuery.data()` and `setAttribute`/`getAttribute` aren't interchangeable. Didn't know that before.

**Comment by zachleat** [comment]
No worries! Thank you for coming back and closing!
